- One Hot Encoding is the technique used to convert categorical variables into numerical format by creating binary for each veriables.

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

In [10]:
df = pd.read_csv("cars.csv")

In [12]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [16]:
df.owner.value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [18]:
df.fuel.value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

## OneHotEncoding using Pandas

In [22]:
pd.get_dummies(df,columns = ['fuel','owner'],dtype = int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [28]:
pd.get_dummies(df,columns = ["fuel", "owner"],dtype = int, drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

## OneHotEncoder using Sklearn

In [32]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train , y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,:-1],test_size = 0.2, random_state = 2)

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
ohe = OneHotEncoder(drop = 'first', sparse_output = False , dtype = np.int32)

In [54]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [61]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [65]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

### OneHotEncoding with Top Categories

In [74]:
counts = df.brand.value_counts()

In [76]:
df['brand'].nunique()
threshold = 100

In [84]:
repl = counts[counts > threshold].index

In [88]:
pd.get_dummies(df['brand'].replace(repl, "uncommon"),dtype = int).sample(5)

,Ambassador,Ashok,Audi,Daewoo,Datsun,Fiat,Force,Isuzu,Jaguar,Jeep,...,Land,Lexus,MG,Mercedes-Benz,Mitsubishi,Nissan,Opel,Peugeot,Volvo,uncommon
4072,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5822,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6752,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3360,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1